spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/van_db?compress=0
    username: default
    password:  # 로컬은 비번 없으면 비워둠 (암호화 불필요)
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  jpa:
    hibernate:
      ddl-auto: none # 중요! ClickHouse는 스키마 자동 생성을 끕니다.
    show-sql: true   # 실행되는 쿼리를 로그로 확인
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  data:
    redis:
      host: localhost
      port: 6379
      # password:

logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB       # 파일 하나당 5MB 넘으면 새로 만듦
      max-history: 30           # 30일 지난 로그는 자동 삭제
      file-name-pattern: logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log

monitoring:
  scheduler:
    rates:
      all: 1000
      success: 5000
      fail: 2000
      cancel: 5000
      high: 5000
      gangnam: 10000
  criteria:
    high-amount: 50000